const { Worker } = require("bullmq");
const IORedis = require("ioredis");
const mongoose = require("mongoose");
const axios = require("axios");
require("dotenv").config();
const express = require("express");

const app = express();

// =====================================================
// REDIS & MONGO CONNECTION
// =====================================================

const connection = new IORedis(process.env.REDIS_URL, {
  maxRetriesPerRequest: null,
  keepAlive: 30000,
  connectTimeout: 10000,
});

mongoose
  .connect(process.env.MONGO_URI)
  .then(() => console.log("✅ Mongo connected"))
  .catch((err) => console.error("❌ Mongo error:", err));

// =====================================================
// MONGOOSE MODEL
// =====================================================

const PRSchema = new mongoose.Schema(
  {
    repo: { type: String, required: true },
    prNumber: { type: Number, required: true },
    action: String,
    title: String,
    author: String,
    aiReview: String,
    riskScore: Number,
  },
  { timestamps: true }
);

PRSchema.index({ repo: 1, prNumber: 1 }, { unique: true });

const PR = mongoose.model("PullRequest", PRSchema);

// =====================================================
// HELPERS
// =====================================================

async function fetchPRDiff(repo, prNumber) {
  const response = await axios.get(
    `https://api.github.com/repos/${repo}/pulls/${prNumber}`,
    {
      headers: {
        Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
        Accept: "application/vnd.github.v3.diff",
      },
    }
  );

  return response.data;
}

async function postCommentToPR(
  repo,
  prNumber,
  aiText,
  riskScore
) {
  try {
    const commentBody = `
## 🧠 NeuroOps AI DevOps Review

**Risk Score:** ${riskScore}/10

---

${aiText}

---

_Generated by NeuroOps AI._
`;

    await axios.post(
      `https://api.github.com/repos/${repo}/issues/${prNumber}/comments`,
      {
        body: commentBody,
      },
      {
        headers: {
          Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
          Accept: "application/vnd.github+json",
        },
      }
    );
  } catch (error) {
    console.error(
      "❌ GitHub Comment Error:",
      error.response?.data || error.message
    );
  }
}

// =====================================================
// AI REVIEW GENERATOR
// =====================================================

async function generateAIReview(diff) {
  const truncatedDiff = diff.slice(0, 12000);

  const prompt = `
Analyze this GitHub pull request diff.

Return sections in this exact format:

### Summary
- concise overview

### Bugs
- possible bugs

### Security
- vulnerabilities or risky patterns

### Performance
- inefficiencies or scaling concerns

### Risk Score
X/10

At the end STRICTLY include:
[FINAL_SCORE: X]

Rules:
- concise bullets only
- no markdown tables
- no long explanations
- prioritize real issues only

DIFF:
${truncatedDiff}
`;

  console.log(
    `⏳ Sending ${truncatedDiff.length} chars to Groq AI...`
  );

  const response = await axios.post(
    "https://api.groq.com/openai/v1/chat/completions",
    {
      model: "llama-3.3-70b-versatile",

      messages: [
        {
          role: "system",
          content:
            "You are an expert DevOps, backend, and security reviewer. Be practical, concise, and accurate.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],

      temperature: 0.3,
      top_p: 1,
      max_tokens: 2000,
      stream: false,
    },
    {
      headers: {
        Authorization: `Bearer ${process.env.GROQ_API_KEY}`,
        "Content-Type": "application/json",
      },

      timeout: 45000,
    }
  );

  const content =
    response.data?.choices?.[0]?.message?.content;

  if (!content) {
    throw new Error("Groq returned empty response");
  }

  return content;
}

// =====================================================
// BULLMQ WORKER
// =====================================================

const worker = new Worker(
  "pr-review-queue",
  async (job) => {
    if (job.name !== "process-pr") {
      console.log(
        `ℹ️ Skipping unknown job name: ${job.name}`
      );
      return;
    }

    console.log(
      `🚀 Processing job ${job.id} for ${job.data.repo}#${job.data.prNumber}`
    );

    const startTime = Date.now();

    try {
      // =========================================
      // FETCH DIFF
      // =========================================

      const diff = await fetchPRDiff(
        job.data.repo,
        job.data.prNumber
      );

      // =========================================
      // AI REVIEW
      // =========================================

      const aiText = await generateAIReview(diff);

      // =========================================
      // LATENCY LOG
      // =========================================

      const duration = (
        (Date.now() - startTime) /
        1000
      ).toFixed(2);

      console.log(
        `⏱️ AI Response received in ${duration}s`
      );

      // =========================================
      // EXTRACT RISK SCORE
      // =========================================

      let extractedScore = 5;

      const tagMatch = aiText.match(
        /\[FINAL_SCORE:\s*(\d+)\]/i
      );

      const sectionMatch = aiText.match(
        /### Risk Score\s*(?:[:\-])?\s*(\d+)/i
      );

      if (tagMatch) {
        extractedScore = parseInt(tagMatch[1]);
      } else if (sectionMatch) {
        extractedScore = parseInt(sectionMatch[1]);
      }

      const finalRiskScore = isNaN(extractedScore)
        ? 5
        : Math.min(Math.max(extractedScore, 0), 10);

      // =========================================
      // SAVE TO DATABASE
      // =========================================

      await PR.findOneAndUpdate(
        {
          repo: job.data.repo,
          prNumber: job.data.prNumber,
        },
        {
          ...job.data,
          aiReview: aiText,
          riskScore: finalRiskScore,
        },
        {
          upsert: true,
          new: true,
        }
      );

      // =========================================
      // OPTIONAL GATEWAY EVENT
      // =========================================

      if (process.env.GATEWAY_URL) {
        await axios
          .post(
            `${process.env.GATEWAY_URL}/api/events/pr-update`,
            {
              repo: job.data.repo,
              prNumber: job.data.prNumber,
              riskScore: finalRiskScore,
            }
          )
          .catch(() => null);
      }

      // =========================================
      // POST COMMENT TO GITHUB
      // =========================================

      await postCommentToPR(
        job.data.repo,
        job.data.prNumber,
        aiText,
        finalRiskScore
      );

      console.log(
        `✅ Job ${job.id} Finished. Risk Score: ${finalRiskScore}. Total time: ${duration}s`
      );
    } catch (error) {
      const errorDuration = (
        (Date.now() - startTime) /
        1000
      ).toFixed(2);

      console.error(
        `❌ Error in job ${job.id} after ${errorDuration}s:`,
        error.response?.data || error.message
      );

      throw error;
    }
  },
  {
    connection,

    concurrency: 1,

    lockDuration: 120000,

    settings: {
      stalledInterval: 60000,
      maxStalledCount: 2,
    },
  }
);

// =====================================================
// WORKER EVENTS
// =====================================================

worker.on("active", (job) => {
  console.log(
    `🏃 Worker is now processing: ${job.id}`
  );
});

worker.on("completed", (job) => {
  console.log(
    `✨ Job ${job.id} completed successfully`
  );
});

worker.on("failed", (job, err) => {
  console.error(
    `🔥 Job ${job?.id} failed:`,
    err.message
  );
});

worker.on("error", (err) => {
  console.error("❌ Critical Worker Error:", err);
});

// =====================================================
// HEALTH ROUTE
// =====================================================

const PORT = process.env.PORT || 5003;

app.get("/health", (req, res) => {
  res.status(200).json({
    status: "ok",
    worker: "running",
    redis: connection.status,
  });
});

app.listen(PORT, () => {
  console.log(
    `📡 Worker service live on ${PORT}`
  );
});