const { Worker } = require("bullmq");
const IORedis = require("ioredis");
const mongoose = require("mongoose");
const axios = require("axios");
require("dotenv").config();
const express = require("express");

const app = express();

// =====================================================
// REDIS & MONGO CONNECTION
// =====================================================

const connection = new IORedis(process.env.REDIS_URL, {
  maxRetriesPerRequest: null,
  keepAlive: 30000, // Sends TCP keepalive every 30s
  connectTimeout: 10000,
});

mongoose
  .connect(process.env.MONGO_URI)
  .then(() => console.log("✅ Mongo connected"))
  .catch((err) => console.error("❌ Mongo error:", err));

const PRSchema = new mongoose.Schema(
  {
    repo: { type: String, required: true },
    prNumber: { type: Number, required: true },
    action: String,
    title: String,
    author: String,
    aiReview: String,
    riskScore: Number,
  },
  { timestamps: true },
);

PRSchema.index({ repo: 1, prNumber: 1 }, { unique: true });
const PR = mongoose.model("PullRequest", PRSchema);

// =====================================================
// HELPERS
// =====================================================

async function fetchPRDiff(repo, prNumber) {
  const response = await axios.get(
    `https://api.github.com/repos/${repo}/pulls/${prNumber}`,
    {
      headers: {
        Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
        Accept: "application/vnd.github.v3.diff",
      },
    },
  );
  return response.data;
}

async function postCommentToPR(repo, prNumber, aiText, riskScore) {
  try {
    const commentBody = `## 🧠 NeuroOps AI DevOps Review\n**Risk Score:** ${riskScore}/10\n---\n${aiText}\n---\n_Generated by NeuroOps AI._`;

    await axios.post(
      `https://api.github.com/repos/${repo}/issues/${prNumber}/comments`,
      { body: commentBody },
      {
        headers: {
          Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
          Accept: "application/vnd.github+json",
        },
      },
    );
  } catch (error) {
    console.error("❌ GitHub Comment Error:", error.message);
  }
}

// =====================================================
// BULLMQ WORKER
// =====================================================
const worker = new Worker(
  "pr-review-queue",
  async (job) => {
    console.log(
      `🚀 Processing job ${job.id} for ${job.data.repo}#${job.data.prNumber}`,
    );

    try {
      const diff = await fetchPRDiff(job.data.repo, job.data.prNumber);
      const truncatedDiff = diff.slice(0, 3500);

      const prompt = `You are an expert DevOps reviewer. Analyze this GitHub PR diff.
Return: ### Summary, ### Bugs, ### Security, ### Performance, and ### Risk Score (X/10).
At the very end of your response, strictly include this tag: [FINAL_SCORE: X]
Keep bullets concise.
DIFF: ${truncatedDiff}`;

      const response = await axios.post(
        "https://integrate.api.nvidia.com/v1/chat/completions",
        {
          model: "moonshotai/kimi-k2.5",
          messages: [{ role: "user", content: prompt }],
          max_tokens: 4096,
          temperature: 1.0,
          top_p: 1.0,
          stream: false,
          chat_template_kwargs: { thinking: true },
        },
        {
          headers: {
            Authorization: `Bearer ${process.env.NVIDIA_API_KEY}`,
            Accept: "application/json",
            "Content-Type": "application/json",
          },
          timeout: 300000,
        },
      );

      const message = response.data?.choices?.[0]?.message;
      const aiText = message?.content || message?.reasoning_content;

      if (!aiText) {
        throw new Error("AI model returned no content or reasoning.");
      }

      let extractedScore = 5;
      const tagMatch = aiText.match(/\[FINAL_SCORE:\s*(\d+)\]/i);
      const sectionMatch = aiText.match(/### Risk Score\s*(?:[:\-])?\s*(\d+)/i);

      if (tagMatch) {
        extractedScore = parseInt(tagMatch[1]);
      } else if (sectionMatch) {
        extractedScore = parseInt(sectionMatch[1]);
      }

      const finalRiskScore = isNaN(extractedScore)
        ? 5
        : Math.min(Math.max(extractedScore, 0), 10);

      await PR.findOneAndUpdate(
        { repo: job.data.repo, prNumber: job.data.prNumber },
        {
          ...job.data,
          aiReview: aiText,
          riskScore: finalRiskScore,
        },
        { upsert: true, new: true },
      );

      if (process.env.GATEWAY_URL) {
        await axios
          .post(`${process.env.GATEWAY_URL}/api/events/pr-update`, {
            repo: job.data.repo,
            prNumber: job.data.prNumber,
            riskScore: finalRiskScore,
          })
          .catch(() => null);
      }

      await postCommentToPR(
        job.data.repo,
        job.data.prNumber,
        aiText,
        finalRiskScore,
      );

      console.log(
        `✅ Job ${job.id} Finished. Risk Score synced at: ${finalRiskScore}`,
      );
    } catch (error) {
      console.error(
        `❌ Error in job ${job.id}:`,
        error.response?.data || error.message,
      );
      throw error;
    }
  },
  {
    connection,
    settings: {
      stalledInterval: 300000,
      maxStalledCount: 1,
      backoff: {
        type: "exponential",
        delay: 15000, // 15s initial retry delay
      },
    },
    // Wait up to 60s when queue is empty before checking again
    drainDelay: 60,
  },
);

worker.on("completed", (job) => console.log(`✨ Job ${job.id} completed`));
worker.on("failed", (job, err) =>
  console.error(`🔥 Job ${job?.id} failed:`, err.message),
);

const PORT = process.env.PORT || 5003;

// Health Check Endpoint
app.get("/health", (req, res) => res.status(200).json({ status: "ok" }));

app.listen(PORT, () => console.log(`📡 Worker service live on ${PORT}`));